### ISSUE TITLE
Display zero value

### ISSUE THREAD

**Issue by yuecen** [kakwa/py-ascii-graph#12]
Hi all,

I run following code for chart displaying.

```
test = [('long_label', 0), ('sl', 0), ('line3', 0)]

graph = Pyasciigraph()
for line in graph.graph('test print', test):
     print line
```

Then, got an unexpected result:

```
ZeroDivisionError: integer division or modulo by zero
```

I know that division by zero has no meaning, however, that should display as follows.

```
test print
###############################################################################
|                                                                   0   long_label
|                                                                   0   sl        
|                                                                   0   line3     
```

I simply modified code with ``__init__.py``, and it works fine. But I don't know if any side effect over there.

```
if max_value == 0:
       number_of_square = 0
else:
       number_of_square = int(value * graph_length / max_value)
```

**Comment by kakwa** [comment]
Fix by commit:
https://github.com/kakwa/py-ascii-graph/commit/ac0921364dccbf5b96fc977c43178bf62e580f0b

(as you proposed)

Version 1.1.4 tagged and published on pypi.
