### ISSUE TITLE
Is it possible to plot pandas dataframe?

### ISSUE THREAD

**Issue by mzfr** [kakwa/py-ascii-graph#20]
Is there a way to plot a Pandas dataframe with this directly to the terminal?

**Comment by kakwa** [comment]
not out of the box.

You could probably do something that export a column and displays it, either by using the library, or by echoing the appropriate format (one '<LABEL>:<VALUE>') in stdout and piping it in the asciigraph command.

Also, this library is more meant to display one dimension data, from what I understand, Pandas dataframes are 2 dimensions datasets. You could however do something like display column by column.
